const variables = {
  url: {
    notPicture: "https://image.freepik.com/foto-gratis/madera-blanca-de-textura-de-fondo_1232-1731.jpg"
  },
  msn: {
    es: {
      error: {
        noDisponible: "Información no disponible",
        errorTypeMime: "Formato de media no reconocido"
      },
      web: "Visita la web",
      idioma: "Español",
      contacto: "Datos de contacto",
      email: "Email",
      fax: "Fax",
      idioma: "Idioma",
      telefono: "Teléfono",
      localizacion: "Localización",
      direccion: "Dirección",
      cp: "Código postal",
      localidad: "Localidad",
      pais: "Pais",
      provincia: "Provincia",
      fotos: "Fotografias",
      descripcion: "Descripción",
      verMapa: "Ver en Google Maps",
      ubicacion: "Ubicación",
      calcularRuta: "Calcular la ruta",
      eligeOpcion: "Selecciona una opción",
      andando: "Andando",
      bici: "Bicicleta",
      coche: "Coche",
      seleccionTransporte: "Selecciona un transporte",
      origen: "Dirección origen",
      destino: "Direccion destino",
      calcularRuta: "Calcular ruta"
    },
    en: {
      error: {
        noDisponible: "Information not available",
        errorTypeMime: "Unrecognized media format"
      },
      web: "Visit the web",
      idioma: "English",
      contacto: "Contact information",
      email: "Email",
      fax: "Fax",
      idioma: "Language",
      telefono: "Phone number",
      localizacion: "Location",
      direccion: "Address",
      cp: "Postal code",
      localidad: "Locality",
      pais: "Country",
      provincia: "Province",
      fotos: "Photos",
      descripcion: "Description",
      verMapa: "See Google Maps",
      ubicacion: "Ubication",
      calcularRuta: "Calculate the route",
      eligeOpcion: "Select a option",
      andando: "Walking",
      bici: "Bicycle",
      coche: "Car",
      seleccionTransporte: "Select a transport",
      origen: "Home address",
      destino: "Destination address",
      calcularRuta: "Calculate route"
    },
    fr: {
      error: {
        noDisponible: "Information non disponible",
        errorTypeMime: "format de média non reconn"
      },
      web: "Visiter le site web",
      idioma: "français",
      contacto: "Contact",
      email: "Envoyer",
      fax: "Fax",
      idioma: "Langue",
      telefono: "Téléphone",
      localizacion: "Lieu",
      direccion: "Adresse",
      cp: "ZIP",
      localidad: "Lieu",
      pais: "Pays",
      provincia: "Province",
      fotos: "Photographies",
      descripcion: "Description",
      verMapa: "Afficher dans Google Maps",
      ubicacion: "Lieu",
      calcularRuta: "Itinéraire",
      eligeOpcion: "Sélectionner une option",
      andando: "Marche",
      bici: "Vélo",
      coche: "Voiture",
      seleccionTransporte: "Transport Sélectionnez",
      origen: "Adresse Source",
      destino: "Adresse de destination",
      calcularRuta: "routage"
    },
    it: {
      error: {
        noDisponible: "Información no disponible",
        errorTypeMime: "Formato de media no reconocido"
      },
      web: "Visita la web",
      idioma: "Español",
      contacto: "Datos de contacto",
      email: "Email",
      fax: "Fax",
      idioma: "Idioma",
      telefono: "Teléfono",
      localizacion: "Localización",
      direccion: "Dirección",
      cp: "Código postal",
      localidad: "Localidad",
      pais: "Pais",
      provincia: "Provincia",
      fotos: "Fotografias",
      descripcion: "Descripción",
      verMapa: "Ver en Google Maps",
      ubicacion: "Ubicación",
      calcularRuta: "Calcular la ruta",
      eligeOpcion: "Selecciona una opción",
      andando: "Andando",
      bici: "Bicicleta",
      coche: "Coche",
      seleccionTransporte: "Selecciona un transporte",
      origen: "Dirección origen",
      destino: "Direccion destino",
      calcularRuta: "Calcular ruta"
    },
    de: {
      error: {
        noDisponible: "Información no disponible",
        errorTypeMime: "Formato de media no reconocido"
      },
      web: "Visita la web",
      idioma: "Español",
      contacto: "Datos de contacto",
      email: "Email",
      fax: "Fax",
      idioma: "Idioma",
      telefono: "Teléfono",
      localizacion: "Localización",
      direccion: "Dirección",
      cp: "Código postal",
      localidad: "Localidad",
      pais: "Pais",
      provincia: "Provincia",
      fotos: "Fotografias",
      descripcion: "Descripción",
      verMapa: "Ver en Google Maps",
      ubicacion: "Ubicación",
      calcularRuta: "Calcular la ruta",
      eligeOpcion: "Selecciona una opción",
      andando: "Andando",
      bici: "Bicicleta",
      coche: "Coche",
      seleccionTransporte: "Selecciona un transporte",
      origen: "Dirección origen",
      destino: "Direccion destino",
      calcularRuta: "Calcular ruta"
    },
    pt: {
      error: {
        noDisponible: "Información no disponible",
        errorTypeMime: "Formato de media no reconocido"
      },
      web: "Visita la web",
      idioma: "Español",
      contacto: "Datos de contacto",
      email: "Email",
      fax: "Fax",
      idioma: "Idioma",
      telefono: "Teléfono",
      localizacion: "Localización",
      direccion: "Dirección",
      cp: "Código postal",
      localidad: "Localidad",
      pais: "Pais",
      provincia: "Provincia",
      fotos: "Fotografias",
      descripcion: "Descripción",
      verMapa: "Ver en Google Maps",
      ubicacion: "Ubicación",
      calcularRuta: "Calcular la ruta",
      eligeOpcion: "Selecciona una opción",
      andando: "Andando",
      bici: "Bicicleta",
      coche: "Coche",
      seleccionTransporte: "Selecciona un transporte",
      origen: "Dirección origen",
      destino: "Direccion destino",
      calcularRuta: "Calcular ruta"
    },
    ru: {
      error: {
        noDisponible: "Información no disponible",
        errorTypeMime: "Formato de media no reconocido"
      },
      web: "Visita la web",
      idioma: "Español",
      contacto: "Datos de contacto",
      email: "Email",
      fax: "Fax",
      idioma: "Idioma",
      telefono: "Teléfono",
      localizacion: "Localización",
      direccion: "Dirección",
      cp: "Código postal",
      localidad: "Localidad",
      pais: "Pais",
      provincia: "Provincia",
      fotos: "Fotografias",
      descripcion: "Descripción",
      verMapa: "Ver en Google Maps",
      ubicacion: "Ubicación",
      calcularRuta: "Calcular la ruta",
      eligeOpcion: "Selecciona una opción",
      andando: "Andando",
      bici: "Bicicleta",
      coche: "Coche",
      seleccionTransporte: "Selecciona un transporte",
      origen: "Dirección origen",
      destino: "Direccion destino",
      calcularRuta: "Calcular ruta"
    }
  },
  idioma: "",
  html: "",
  arrayEstructura: [],
  map: null,
  travelMode: null,
  destino: null
};

export default variables;